### ISSUE TITLE
[!] Unable to satisfy the following requirements -> Cocoapods+Swift3

### ISSUE THREAD

**Issue by dm-katsubo** [Alamofire/AlamofireNetworkActivityIndicator#11]
Update please .podspecs  for swift3 branch. Now I get an error: 

> [!] Unable to satisfy the following requirements:
> 
> - `Alamofire (from `https://github.com/Alamofire/Alamofire.git`, branch `swift3`)` required by `Podfile`
> - `Alamofire (~> 3.3)` required by `AlamofireNetworkActivityIndicator (1.0.1)`

thanks!

**Comment by cnoon** [comment]
Fixed in 9cf749df @dm-katsubo. 

Cheers. 🍻

**Comment by vineetshah** [comment]
Hi @cnoon, I'm still experiencing a similar issue on the `swift3` branch:

> [!] Unable to satisfy the following requirements:
> 
> - `Alamofire (from `https://github.com/Alamofire/Alamofire.git`, branch `swift3`)` required by `Podfile`
> - `Alamofire (= 4.0.0-beta.1)` required by `AlamofireNetworkActivityIndicator (2.0.0-beta.1)`
> 
> Specs satisfying the `Alamofire (from `https://github.com/Alamofire/Alamofire.git`, branch `swift3`), Alamofire (= 4.0.0-beta.1)` dependency were found, but they required a higher minimum deployment target.
